# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter build appbundle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.2'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: sudo apt-get -y install xvfb xorg gtk2-engines-pixbuf
      - name: test
        env:
          TEST_INSTANCE_URL: ${{ secrets.TEST_INSTANCE_URL }}
        run: |
          chromedriver --port=4444 &
          flutter drive \
            --dart-define=ELN_USERNAME=complat.user1@eln.edu \
            --dart-define=ELN_PASSWORD=@complat \
            --dart-define=ELN_URL=$TEST_INSTANCE_URL \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/app_test.dart \
            -d web-server --browser-name=chrome --web-browser-flag "--disable-web-security --headless" --headless

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.2'
      - run: flutter pub get
      - run: flutter build apk --release
      
      - name: set local properties
        run: | 
          echo "" >> ./android/local.properties
          echo flutter.minSdkVersion=21 >> ./android/local.properties
          echo flutter.targetSdkVersion=33 >> ./android/local.properties
          echo flutter.compileSdkVersion=33 >> ./android/local.properties

      - name: set key properties
        # keyPassword="${{ secrets.KEY_PASSWORD }}"
        # storePassword="${{ secrets.STORE_PASSWORD }}"
        # keyAlias="${{ secrets.KEY_ALIAS }}
        # storeFile=keystore.jks
        run: |
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" > ./android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> ./android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> ./android/key.properties
          echo "storeFile=keystore.jks" >> ./android/key.properties
          echo "${{ secrets.KEY_JKS }}" | base64 --decode > ./android/app/keystore.jks
          echo 

      
      - run: flutter build appbundle

      - name: Upload aab artefact
        uses: actions/upload-artifact@v4
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab

      # Add APk to assets
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN_SECRET }}